// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT MANUALLY EDIT ITS CONTENTS.

export interface IRouteTable {
    readonly deleteFoodTruck: string;
    readonly getFoodTruckMenu: string;
    readonly getFoodTrucks: string;
    readonly getFoodTruckSchedule: string;
}

export const routes: IRouteTable = {
    deleteFoodTruck: '/FoodTrucks/DeleteTruck',
    getFoodTruckMenu: '/FoodTrucks/GetMenu',
    getFoodTrucks: '/FoodTrucks/GetTrucks',
    getFoodTruckSchedule: '/FoodTrucks/GetSchedule',
};

export default routes;
